// Auto-generated by scripts/scan-automations.ts
// Do not edit manually. Run: bun scripts/scan-automations.ts

export interface AutomationManifestEntry {
  id: string
  filePath: string
  routePath: string
  type: 'cron' | 'webhook' | 'integration' | 'portal-action' | 'event-action'
  cronSchedule?: string
  httpMethod: string
  usesWrapper: boolean
  /** AI-generated summary. Edit in this file if wrong. */
  summary: string
}

export const AUTOMATIONS: AutomationManifestEntry[] = 
[
  {
    "id": "cron/room-availability",
    "filePath": "app/api/cron/room-availability/route.ts",
    "routePath": "/api/cron/room-availability",
    "type": "cron",
    "cronSchedule": "* * * * *",
    "httpMethod": "GET",
    "usesWrapper": false,
    "summary": "Updates Discord message with real-time meeting room availability from Airtable bookings"
  },
  {
    "id": "cron/rotate-door-code",
    "filePath": "app/api/cron/rotate-door-code/route.ts",
    "routePath": "/api/cron/rotate-door-code",
    "type": "cron",
    "cronSchedule": "0 17 * * 1",
    "httpMethod": "GET",
    "usesWrapper": true,
    "summary": "Rotates weekly Verkada door code, updates Discord channel name and posts notification"
  },
  {
    "id": "day-pass/activate/api",
    "filePath": "app/day-pass/activate/api/route.ts",
    "routePath": "/day-pass/activate/api",
    "type": "event-action",
    "httpMethod": "POST",
    "usesWrapper": false,
    "summary": "Activates a purchased day pass, sets date and reveals door code"
  },
  {
    "id": "eag26/register",
    "filePath": "app/eag26/api/register/route.ts",
    "routePath": "/eag26/api/register",
    "type": "event-action",
    "httpMethod": "POST",
    "usesWrapper": false,
    "summary": "Registers EAG attendees for day pass access, creates Airtable record and sends welcome email"
  },
  {
    "id": "forkable-sync",
    "filePath": "app/api/forkable-sync/route.ts",
    "routePath": "/api/forkable-sync",
    "type": "integration",
    "httpMethod": "POST",
    "usesWrapper": true,
    "summary": "Adds members to Forkable meal club when Airtable tier changes to Private Office or Program"
  },
  {
    "id": "portal/bulk-sync-discord-roles",
    "filePath": "app/portal/api/bulk-sync-discord-roles/route.ts",
    "routePath": "/portal/api/bulk-sync-discord-roles",
    "type": "portal-action",
    "httpMethod": "POST",
    "usesWrapper": false,
    "summary": "Staff-only bulk sync of all members' Discord roles to match their Airtable tiers"
  },
  {
    "id": "portal/pause-subscription",
    "filePath": "app/portal/api/pause-subscription/route.ts",
    "routePath": "/portal/api/pause-subscription",
    "type": "portal-action",
    "httpMethod": "POST, DELETE",
    "usesWrapper": false,
    "summary": "Pauses or resumes a member's Stripe subscription and notifies staff via email"
  },
  {
    "id": "portal/send-magic-link",
    "filePath": "app/portal/api/send-magic-link/route.ts",
    "routePath": "/portal/api/send-magic-link",
    "type": "portal-action",
    "httpMethod": "POST",
    "usesWrapper": false,
    "summary": "Sends passwordless login email with magic link token, rate-limited to 3 per 15 min"
  },
  {
    "id": "portal/sync-discord-role",
    "filePath": "app/portal/api/sync-discord-role/route.ts",
    "routePath": "/portal/api/sync-discord-role",
    "type": "portal-action",
    "httpMethod": "POST",
    "usesWrapper": false,
    "summary": "Syncs a single member's Discord role to match their Airtable tier"
  },
  {
    "id": "webhooks/discord",
    "filePath": "app/api/webhooks/discord/route.ts",
    "routePath": "/api/webhooks/discord",
    "type": "webhook",
    "httpMethod": "POST",
    "usesWrapper": false,
    "summary": "Handles Discord interaction webhooks (slash commands, verifications)"
  },
  {
    "id": "webhooks/stripe",
    "filePath": "app/api/webhooks/stripe/route.ts",
    "routePath": "/api/webhooks/stripe",
    "type": "webhook",
    "httpMethod": "POST",
    "usesWrapper": false,
    "summary": "Handles Stripe events: day pass purchases create Airtable records and send activation emails; new subscriptions add members to Forkable"
  }
]
